### ISSUE TITLE
Online live test

### ISSUE THREAD

**Issue by npracht** [mautic/mautic-tester#4]
# Needs
It is not very easy to install for a non dev user (you need a serveur, git installed, etc.).
It would be awesome to be able to install a mautic free SaaS version to test the PRs and then have a button to delete the instance in case of crash or stuff like that.
Then for a marketer (as i am), it is very very easy to test all the ready to test PRs on github.com/mautic/mautic/pulls !

@dbhurley what do you think ?

**Comment by dbhurley** [comment]
Hahahaha, mercy, you're never satisfied! 

No. We're not going to lower the bar that far at the moment, we still need developers to be doing the testing of the code, that's first priority. 2 marketers testing the code is NOT acceptable from a coding standpoint. We need devs in the code more.

**Comment by npracht** [comment]
I am satisfied ! It is very great and we are going to try to install it on certain instances.
I thought user testing is also very important to test/reproduce bugs.

Then yes simply close it if you think this is not interesting.
